A simple battery app.
emfcamp/TiDAL-Firmware pull request #41
Opened 2022-05-08 19:10 UTC by craftit

2022-05-09 12:14 UTC, kliment requested changes
Charging status logic is the wrong way around. Button detection should trigger when voltage read is below UVLO threshold (will read as close to zero) and not attempt to report battery status in that case.

2022-05-09 13:22 UTC, tomsci commented on modules/battery/__init__.py
> +        window.cls()
minor: `cls()` should be getting called as a result of the `super().on_activate()` call (which calls `TextWindow.redraw()`) so this shouldn't be needed here?

2022-05-11 19:51 UTC, craftit commented
The raw voltage should probably be removed in the final version, but it is helpful for testing so I'll leave it in.

2022-05-11 22:17 UTC, tomsci commented on modules/battery/__init__.py
> +        # We should probably disable interrupts from the pin too here.
Unless you've set an interrupt on BUTTON_A yourself (by calling `Buttons.on_press()` or `on_up_down()`), the app switching mechanism will guarantee nobody else has an active interrupt on it between calls to on_activate() and on_deactivate().

2022-05-11 22:29 UTC, tomsci approved these changes
App seems to work nicely for me

2022-05-12 04:16 UTC, kliment approved these changes

2022-05-12 04:16 UTC, merged